name: push-result-to-discord
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    outputs:
      summary: ${{ steps.summary.outputs.file }}
      #results: ${{ steps.results.outputs.file }}
    defaults:
      run:
        working-directory: ./code
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - run: pip install --user numpy
      - run: mkdir etc
      - run: python prisonersDilemma.py --no-cache
      - id: summary
        run: |
            output="$(cat summary.txt)"
            output="${output//'%'/'%25'}"
            output="${output//$'\n'/'%0A'}"
            output="${output//$'\r'/'%0D'}"
            echo "::set-output name=file::$output"
      - id: results
        run: |
            output="$(cat results.html)"
            output="${output//'%'/'%25'}"
            output="${output//$'\n'/'%0A'}"
            output="${output//$'\r'/'%0D'}"
            echo "::set-output name=file::$output"
      - run: |
            mkdir public
            cp results.html public/index.html
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: code/public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  publish:
    runs-on: ubuntu-latest
    needs: run
    steps:
      - env:
            DISCORD_WEBHOOK: ${{ secrets.WEBHOOK_URL }}
            DISCORD_USERNAME: THE DOG IS BACK YAY
            #DISCORD_AVATAR: https://cdn.discordapp.com/icons/844706669455343616/e1075eb0f262c1df130e1156dc59b39b.png?size=4096
            DISCORD_AVATAR: https://cdn.discordapp.com/avatars/844832331356700732/b495659750b3253eaf771972b14f60a4.png?size=256
        uses: bs2kbs2k/action-discord@master
        with:
            args: ${{ needs.run.outputs.summary }}
